In [13]:
import numpy as np
print('----------op.reduce-----------')
a=np.array([1,2,3,4,5,6,7])
print(np.add.reduce(a))

b= np.array(['ab','cd','ef'],dtype='object')
print(np.add.reduce(b))

c = np.arange(3) + np.arange(0, 40,10).reshape(-1, 1)
print(c)
print(np.add.reduce(c,1))
print('----------op.reduceat-----------')
indices=np.array([1,4])
print(np.add.reduceat(a,indices))

print('----------op.accumelate-----------')


----------op.reduce-----------
28
abcdef
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[ 3 33 63 93]
----------op.reduceat-----------
[ 9 18]
----------op.accumelate-----------


In [14]:
print('----------op.outer-----------')
a=np.array([1,2,3,4,5,6,7])
b=np.array([1,2,3,4])
np.add.outer(a,b)

----------op.outer-----------


array([[ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11]])