In [1]:
import numpy as np

In [12]:
a=np.array([[1,2,3,4],
        [5,6,7,8]
])
print(np.sum(a))
print(a.sum())
print(np.sum(a,axis=0))
print(np.sum(a,axis=1))
print(a.mean())


36
36
[ 6  8 10 12]
[10 26]
4.5


In [24]:
print(a.min())
print(a.max())
print(np.min(a,axis=0))
print(np.max(a,axis=1))
print(a.argmin())
print(a.argmax())
print(np.argmin(a,axis=0))
print(a.argmax(axis=1))
print(np.unravel_index(a.argmax(),a.shape))

1
8
[1 2 3 4]
[4 8]
0
7
[0 0 0 0]
[3 3]
(1, 3)


In [39]:
a=np.arange(-2,2) ** 2
print(a)
mask=a % 2== 0
print(mask)
np.where (mask)

positive=np.arange(1,5)
negative=-positive
print(np.where(mask,positive,negative))
print(np.where(mask,1,0))
print(np.where(mask,positive,1))

[4 1 0 1]
[ True False  True False]
[ 1 -2  3 -4]
[1 0 1 0]
[1 1 3 1]


In [53]:
a = np.arange(-15, 15).reshape(5, 6) ** 2
print(a)
print('\nThe maximum of each row is:',np.max(a,axis=1))
print('The mean of each column is:',np.mean(a,axis=0))
print('The position of the overall minimum is:',a.argmin())


[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]

The maximum of each row is: [225  81   9  64 196]
The mean of each column is: [81. 76. 73. 72. 73. 76.]
The position of the overall minimum is: 15


In [72]:
a=np.ones((3,5))
print(a)
b=np.ones((5,))
print(b)
b.reshape(1,5)
b[np.newaxis, :]
print(b.shape)
c=a+b
print(c.shape)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[1. 1. 1. 1. 1.]
(5,)
(3, 5)
