## Simple Array Creation

In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3,4,5])
b=np.array([6,7,8,9,10])
print(a.dtype)
print(a.ndim)


int32
1


In [3]:
c=a+b
c

array([ 7,  9, 11, 13, 15])

In [4]:
d=a-b
d

array([-5, -5, -5, -5, -5])

In [5]:
e=a*b
e

array([ 6, 14, 24, 36, 50])

In [6]:
f=a ** b
f

array([      1,     128,    6561,  262144, 9765625])

In [7]:
np.sin(f)
# print(y)

array([ 0.84147098,  0.72103771,  0.97670744, -0.08410703,  0.05569178])

In [8]:
a[2]=22
a

array([ 1,  2, 22,  4,  5])

In [9]:
a=np.array([[0,1,2,3,4],[5,6,7,8,9]])
a.shape

(2, 5)

In [10]:
a.ndim

2

In [11]:
a[0,3]

3

In [12]:
b=np.array([[[0,1,2,3,4],[5,6,7,8,9],[22,33,44,55,66]]])
b.ndim

3

In [13]:
b.shape

(1, 3, 5)

In [14]:
b[0,2,2]

44

In [15]:
a= np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
a=np.array([1,2,3,4,5,6])
a[0:3]

array([1, 2, 3])

In [17]:
a[-3:5]

array([4, 5])

In [18]:
b=np.arange(25).reshape(5,5)
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [19]:
a=np.arange(0,56).reshape(7,8)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29, 30, 31],
       [32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47],
       [48, 49, 50, 51, 52, 53, 54, 55]])

In [20]:
a[0:,3:6:2]

array([[ 3,  5],
       [11, 13],
       [19, 21],
       [27, 29],
       [35, 37],
       [43, 45],
       [51, 53]])

In [21]:
a[2:3:1,6:8:1]

array([[22, 23]])

In [22]:
a[6:7:1,7:8:1]

array([[55]])

In [23]:
a[2:4:1,1:3:1]

array([[17, 18],
       [25, 26]])

In [24]:
a[2:4,1:3]

array([[17, 18],
       [25, 26]])

In [25]:
a[5:6,4:6]

array([[44, 45]])

In [26]:
a[5:7,6:8]

array([[46, 47],
       [54, 55]])

In [27]:
a[0:,1:7:5]

array([[ 1,  6],
       [ 9, 14],
       [17, 22],
       [25, 30],
       [33, 38],
       [41, 46],
       [49, 54]])

In [28]:
a[0:,1]

array([ 1,  9, 17, 25, 33, 41, 49])