In [46]:
import numpy as np

### Basic Array Creation

# Creatation of List
create List in python? # Check Type of list

In [47]:
# Code here

# creation of list
list=[1,2,3,4,5]
# print the type of list
print(type(list))

<class 'list'>


# Creatation of Arrays
1.Create an array containing 10 elements 

2.Checking array "TYPE"

3.Check data type of array elements

4.Array dim

5.Array Shape

6.Bytes per element

7.Total bytes in an Array

In [48]:
# Create 'int' array and repeat above mention steps 1-7
# Answer Here
# Step 1
a=np.array([1,2,3,4,5,6,7,8,9,10])

# Step 2
print('Array Type :',type(a))

# Step 3
print('Data Type of array elements :',a.dtype)

# Step 4
print('The Dimension of array is :',a.ndim)

# Step 5
print('The Shape of array is :',a.shape)

# Step 6
print('The Bytes per elements are :',a.itemsize)

# step 7
print('The total number of bytes are :',a.nbytes)

Array Type : <class 'numpy.ndarray'>
Data Type of array elements : int32
The Dimension of array is : 1
The Shape of array is : (10,)
The Bytes per elements are : 4
The total number of bytes are : 40


In [49]:
# Create 'float' array and repeat above mention steps 1-7
#Answer Here
# Step 1
b = np.array([1.1, 2.2, 3.3, 4.4, 5.5, 6.6, 7.7, 8.8, 9.9, 10.0])

# Step 2
print('Array Type :', type(b))

# Step 3
print('Data Type of array elements :', b.dtype)

# Step 4
print('The Dimension of array is :', b.ndim)

# Step 5
print('The Shape of array is :', b.shape)

# Step 6
print('The Bytes per elements are :', b.itemsize)

# Step 7
print('The total number of bytes are :', b.nbytes)


Array Type : <class 'numpy.ndarray'>
Data Type of array elements : float64
The Dimension of array is : 1
The Shape of array is : (10,)
The Bytes per elements are : 8
The total number of bytes are : 80


-Try to assign a float into an int32

-Use .fill function # fill has the same behavior


In [61]:
# Answer here
# Step 1: Create an integer array
c = np.array([1, 2, 3, 4, 5], dtype=np.int32)

# Step 2: Use the .fill() function to fill the array with a float (1.1)
c.fill(1.1)

# Step 3: Print the array
print(c)

[1 1 1 1 1]


-. Add two  arrays

-. Multiple both arrays

-.Use ** operator in array operation

-.Create array from 0.0 to 11.0

-.Multiply entire array with a scalar value
 c = (2.0 * np.pi)

-.Use np.arrange function to create an array with step of 0.5 from 1.0 to 3.0

In [88]:
# Answer Here
x=np.array([1,2,3,4,5,])
y=np.array([11,12,13,10,15])

# step 1
print('Addition of arrays :')
print('x + y =',x+y)

# step 2
print('Multiplication of arrays :')
print('x * y =',x*y)

# step 3
print('Operator in array :')
print('x ** y =')
print(x ** y)

# step 4
d = np.arange(0.0, 12.0, 1.0)  # step size of 1.0
# Set print options to show the decimal point
np.set_printoptions(precision=1, suppress=True)
# Print the array
print("Array d:", d)

# Step 5
# Create an array from 0.0 to 11.0
d = np.arange(0.0, 12.0, 1.0)
# Print the array with one decimal place
print("Array d:", np.array2string(d, formatter={'float_kind':lambda x: f"{x:.1f}"}))

# Step 6
c=2.0*np.pi
x=c*x
print("Array multiplied by 2pi:",x)

# Step 7
f=np.arange(1.0,3.5,0.5)
print("Array :",np.array2string(f, formatter={'float_kind':lambda x: f"{x:.1f}"}))


Addition of arrays :
x + y = [12 14 16 14 20]
Multiplication of arrays :
x * y = [11 24 39 40 75]
Operator in array :
x ** y =
[        1      4096   1594323   1048576 452807053]
Array d: [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]
Array d: [0.0 1.0 2.0 3.0 4.0 5.0 6.0 7.0 8.0 9.0 10.0 11.0]
Array multiplied by 2pi: [ 6.3 12.6 18.8 25.1 31.4]
Array : [1.0 1.5 2.0 2.5 3.0]


# Slicing
var[lower:upper:step]
• Extracts a portion of a sequence by specifying a lower and upper bound.

• The lower-bound element is included, but the upper-bound element is not included.

• Mathematically: [lower, upper). The step value specifies the stride between elements.

1. Etract array indices from 1 to 3:
2. Use negative indices as well
3. Omitted boundaries are assumed to be the beginning (or end) of the array grab first three elements
4. Grab last two elements
5. Grab every other element
6. slicing the last two elements returns the data there
7. Can we insert an iterable of length two? or a scalar value
8.Arrays created by slicing share data with the originating array. Changing values in a slice also changes the original array.
For example create a slice containing two elements of a changing b changed a! Have an experiment
9. if an array a = [[0, 1, 2, 3, 4],[1, 2, 3, 4, 5]] extract values from row 1 to onward and from col 0, 2 and 4.
10. Perform some masking on a = np.arange(0,36).reshape(6,6)
with mask = np.array([1, 0, 1, 0, 0, 1])


In [166]:
# code here
# Array for examples
a = np.array([1,2,3,4,5,6,7,8,9,10])
# Step 1 
# Extract array indices from 1 to 3
extracted_1_to_3 = a[1:4]
print("Extracted indices from 1 to 3:", extracted_1_to_3)

# Step 2 
# Use negative indices
negative_indices = a[-3:-1]
print("Extracted with negative indices:", negative_indices)

# Step 3
# Grab First three elements
first_three = a[0:3]
print("First three elements:", first_three)

# Step 4
# Grab last two elements
last_two = a[-2:]
print("\nLast two elements:", last_two)

# Step 5
# Grab every other element
every_other = a[0:11:2]
print("\nEvery other element:", every_other)

# Step 6
# Slicing the last two elements
last_two_slice = a[:-2]
print("\nSlicing the last two elements:", last_two_slice)

# Step 7

# Create an original array
original_array = np.array([1, 2, 3, 4, 5])

# Create a slice that contains two elements from the original array
sliced_array = original_array[1:3]

print("\nOriginal Array before change:", original_array)
print("Sliced Array before change:", sliced_array)

# Change a value in the sliced array
sliced_array[0] = 99  # Change the first element of the sliced array

print("\nOriginal Array after change:", original_array)
print("Sliced Array after change:", sliced_array)


# Step 8:
b = np.array([
            [0, 1, 2, 3, 4],
            [1, 2, 3, 4, 5]
            ])
# Extract values from row 1 to onward and from col 0, 2, and 
extracted_from_b = b[0:, [0, 2, 4]]
print("\nExtracted values from b :\n", extracted_from_b)

# 9. Perform some masking on a = np.arange(0,36).reshape(6,6)
mask = np.array([1, 0, 1, 0, 0, 1])
g = np.arange(0, 36).reshape(6, 6)
masked_array = g[mask == 1]  # Apply mask
print("Masked array:\n", masked_array)

Extracted indices from 1 to 3: [2 3 4]
Extracted with negative indices: [8 9]
First three elements: [1 2 3]

Last two elements: [ 9 10]

Every other element: [1 3 5 7 9]

Slicing the last two elements: [1 2 3 4 5 6 7 8]

Original Array before change: [1 2 3 4 5]
Sliced Array before change: [2 3]

Original Array after change: [ 1 99  3  4  5]
Sliced Array after change: [99  3]

Extracted values from b :
 [[0 2 4]
 [1 3 5]]
Masked array:
 [[ 0  1  2  3  4  5]
 [12 13 14 15 16 17]
 [30 31 32 33 34 35]]


### Create a 2-D array where the first row goes from 10 to 80 exclusive with steps of 5 and 2nd row goes from 5 to 47 exclusive with steps of 3

In [134]:
#code here
# Create the first row
row1 = np.arange(10, 85, 5)

# Create the second row
row2 = np.arange(5, 48, 3)

# Combine the rows into a 2-D array
h = np.array([row1, row2])

print(h)

[[10 15 20 25 30 35 40 45 50 55 60 65 70 75 80]
 [ 5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]]


### Now use indexing to select the 5th 7th and 11th columns

In [135]:
# code here
h[:, [4, 6, 10]]

array([[30, 40, 60],
       [17, 23, 35]])

### Select the 2nd row and fourth-last to second-last columns

In [138]:
# code here
h[1:,-4:-1]

array([[38, 41, 44]])

### Select 3rd to 3rd last columns skipping every second column

In [141]:
# code here
h[0:,2:-2:2]

array([[20, 30, 40, 50, 60, 70],
       [11, 17, 23, 29, 35, 41]])

###  Select 3rd to 3rd last columns skipping every second column but in reverse order

In [146]:
# code here
h[:, 2:-2:2][:, ::-1]

array([[70, 60, 50, 40, 30, 20],
       [41, 35, 29, 23, 17, 11]])

### Zip Operations on Numpy Arrays
Use a zip function on two arrys.

Create another array which would be the sum of corresponding elements of two arrays using for loop.

In [157]:
a = [1, 2, 3, 4]
b = [2, 3, 4, 5]

# Answer Here

# Define two arrays
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

# Use zip
zipped = zip(a, b)

# Create a new array to hold the sums
sum_array = []

# use for loop
for x, y in zipped:
    sum_array.append(x + y)

print("Array A:", a)
print("Array B:", b)
print("Sum of corresponding elements:", sum_array)


Array A: [1 2 3 4]
Array B: [5 6 7 8]
Sum of corresponding elements: [6, 8, 10, 12]


In [156]:
#For loop to add corresponding elements in two lists

# Answer Here
# Create an empty list to hold the sums
sum_list = []

# Use a for loop
for i in range(len(a)):
    sum_list.append(a[i] + b[i])

print("List A:", a)
print("List B:", b)
print("Sum of corresponding elements:", sum_list)


List A: [1 2 3 4]
List B: [5 6 7 8]
Sum of corresponding elements: [6, 8, 10, 12]
