In [1]:
import numpy as np

# Q1

Statement: Given a 3D NumPy array arr of shape (2, 3, 4), write a code snippet to calculate the sum of all elements in the array.

Sample Input:

In [12]:
# Answer Here
a = np.arange(24).reshape(2, 3, 4)
print(a)
a.ndim


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


3

# Q2

Statement: Write a NumPy code snippet to create a 4D array arr of shape (2, 3, 4, 5) filled with random integers ranging from 0 to 9.

Sample Output:

In [22]:
# Answer Here
# 4D array of shape (2, 3, 4, 5)
arr = np.random.randint(0, 10, size=(2, 3, 4, 5))

# Print the array
print("4D array with random integers from 0 to 9:")
print(arr)

4D array with random integers from 0 to 9:
[[[[5 7 2 7 5]
   [7 7 4 5 4]
   [0 8 0 5 5]
   [7 9 8 9 1]]

  [[9 3 6 5 5]
   [1 3 2 0 8]
   [0 3 7 2 2]
   [6 9 5 0 5]]

  [[0 4 2 5 2]
   [8 6 8 0 6]
   [3 8 0 1 7]
   [5 3 3 6 8]]]


 [[[5 7 9 6 2]
   [3 3 8 3 4]
   [2 7 0 9 4]
   [2 3 6 6 9]]

  [[7 4 9 7 7]
   [2 4 9 8 4]
   [4 7 5 2 9]
   [1 3 8 8 7]]

  [[6 4 7 0 5]
   [6 8 8 8 1]
   [7 9 2 8 9]
   [3 3 3 4 6]]]]


# Q3

Statement: Given a 4D NumPy array arr of shape (2, 3, 4, 5), write a code snippet to calculate the mean along the second axis.

Sample Input:

In [21]:
arr = np.random.rand(2, 3, 4, 5)

# Calculate the mean along the second axis
mean_along_axis_2 = np.mean(arr, axis=1)

# Print the result
print("Mean along the second axis:")
print(mean_along_axis_2)

Mean along the second axis:
[[[0.50928836 0.59684982 0.41626773 0.75776843 0.62457447]
  [0.36462024 0.43826657 0.61445258 0.54134789 0.28621702]
  [0.80939644 0.5041388  0.52263068 0.20299855 0.55606217]
  [0.25386461 0.62385145 0.54354017 0.47553287 0.57690738]]

 [[0.19151639 0.33976559 0.47331376 0.67482044 0.58970646]
  [0.08289746 0.5733327  0.49795926 0.93509416 0.42229765]
  [0.68459876 0.71759307 0.49061488 0.50052138 0.58410813]
  [0.33568648 0.81162972 0.35189142 0.68066526 0.1633363 ]]]


# Q4

Statement: You have collected data from a temperature sensor placed at different locations over a period of time. The recorded temperatures are stored in a 3D NumPy array temps of shape (7, 24, 60), where the dimensions represent the number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the average temperature for each day.

Sample Input:

In [20]:
temps = np.random.rand(7, 24, 60)

# Calculate the average temperature for each day
average_temp_per_day = np.mean(temps, axis=(1, 2))

# Print the result
print("Average temperature for each day:")
print(average_temp_per_day)

Average temperature for each day:
[0.49001842 0.50607485 0.49056858 0.49452713 0.49224544 0.49636101
 0.51115822]


Sample Output:

array([27.43864059, 26.99643944, 27.10398301, 27.43854821, 26.81072977,
       26.76581481, 27.07946152])

# Q5

Statement: You have collected data from multiple sensors placed in different rooms of a building. The sensor readings are stored in a 4D NumPy array readings of shape (4, 7, 24, 60), where the dimensions represent the number of sensors, number of days, hours in a day, and minutes in an hour, respectively. Write a code snippet to calculate the maximum reading for each sensor across all days.

In [19]:
readings = np.random.rand(4, 7, 24, 60)

# Calculate the maximum reading for each sensor across all days
max_readings_per_sensor = np.max(readings, axis=(1, 2, 3))

# Print the result
print("Maximum readings for each sensor across all days:")
print(max_readings_per_sensor)

Maximum readings for each sensor across all days:
[0.99973468 0.9999922  0.99980911 0.99999395]


# Q6

Statement: You have collected data from a 3D printer that measures the dimensions of printed objects. The recorded dimensions are stored in a 3D NumPy array dimensions of shape (100, 50, 3), where the dimensions represent the number of printed objects, number of measurements for each object, and the three dimensions (length, width, height), respectively. Write a code snippet to calculate the average length, width, and height across all objects.

Sample Input:

In [23]:
# Answer Here
dimensions = np.random.rand(100, 50, 3)

# Calculate the average for length, width, and height across all objects
average_dimensions = np.mean(dimensions, axis=(0, 1))

# Print the result
print("Average dimensions (length, width, height):")
print(average_dimensions)

Average dimensions (length, width, height):
[0.50349019 0.4997165  0.50237667]


# Q7

Statement: You are given a 3D NumPy array data of shape (5, 6, 7) representing the sensor readings from multiple sensors placed in different locations over a period of time. Each sensor provides measurements at different time points. Write a code snippet to calculate the following statistics for each sensor:

Total number of measurements

Average measurement value

Standard deviation of measurements

Minimum measurement value

Maximum measurement value

Sample Input:

In [24]:
# Answer Here
data = np.random.rand(5, 6, 7)
# Calculate statistics for each sensor
total_measurements = data.shape[1] * data.shape[2]
average_measurements = np.mean(data, axis=(1, 2))
std_dev_measurements = np.std(data, axis=(1, 2))
min_measurements = np.min(data, axis=(1, 2))
max_measurements = np.max(data, axis=(1, 2))

# Print the results
print("Total number of measurements for each sensor:", total_measurements)
print("Average measurement value for each sensor:", average_measurements)
print("Standard deviation of measurements for each sensor:", std_dev_measurements)
print("Minimum measurement value for each sensor:", min_measurements)
print("Maximum measurement value for each sensor:", max_measurements)

Total number of measurements for each sensor: 42
Average measurement value for each sensor: [0.5706825  0.43491537 0.51283344 0.44199337 0.55380287]
Standard deviation of measurements for each sensor: [0.29556896 0.25607454 0.28304752 0.31304721 0.31569569]
Minimum measurement value for each sensor: [0.00879311 0.01935095 0.01124311 0.01556789 0.03773057]
Maximum measurement value for each sensor: [0.9902783  0.955482   0.98621323 0.99835977 0.99318628]
