# Numpy Basics Exercises

Please complete the following exercises **using numpy only**.

# Array Functions
1.Arange([start,] stop[, step],dtype=None)
Nearly identical to Python’s range(). Creates an array of values in the range [start,stop) with the specified step value. Allows non-integer values for start, stop, and step. Default dtype is derived from the start, stop, and step values. create an array with arange.

In [144]:
import numpy as np

In [145]:
# code here (you may create an array of your own choice)
a=np.arange(1,21,1).reshape(5,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

2.Create arrays with ONES, ZEROS, shape is a number or sequence specifying the dimensions of the array. If dtype is not specified, it defaults to float64.

In [146]:
# code here (you may create an array of your choice of size)
b=np.ones((3,5))
print(b)
c=np.zeros((3,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


3.Generate an n by n identity array. The default dtype is float64.

In [147]:
# code here (you may create an array of your choice of size)
d=np.identity(4)
print(d)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


4.use empty, full, and fill, max, min, std, mean, var, argmax, linspace

In [148]:
# code here (use the array createed in Question 1 for this)
empty=np.empty(a.shape)
print('\nEmpty:',empty)

full=np.full(a.shape,7)
print('\nFull:',full)

empty.fill(5)
print('\nFill:',empty)

min=np.min(a)
print("Minimum :",min)

max=np.max(a)
print("Maximum :",max)

std=np.std(a)
print("Standard Deviation =",std)

mean=np.mean(a)
print("Mean =",mean)

varience=np.var(a)
print("Varience =",varience)

argmax=np.argmax(a)
print("Argmax =",mean)

linespace=np.linspace(1,20,5)
print("Linespace =",linespace)


Empty: [[90.25 72.25 56.25 42.25]
 [30.25 20.25 12.25  6.25]
 [ 2.25  0.25  0.25  2.25]
 [ 6.25 12.25 20.25 30.25]
 [42.25 56.25 72.25 90.25]]

Full: [[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]

Fill: [[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
Minimum : 1
Maximum : 20
Standard Deviation = 5.766281297335398
Mean = 10.5
Varience = 33.25
Argmax = 10.5
Linespace = [ 1.    5.75 10.5  15.25 20.  ]


5. Create the array below with a = np.arange(-15, 15).reshape(5, 6) ** 2

  Rule 1:
  Operations between multiple array objects are first checked for proper shape match.

  Rule 2:
  Mathematical operators (+ - * / exp, log, ...) apply element by element, on the values.

  Rule 3:
  Reduction operations (mean, std, skew, kurt, sum, prod, ...) apply to the whole array, unless an axis is specified.

  Rule 4:
  Missing values propagate unless explicitly ignored (nanmean, nansum, ...).

In [149]:
''' code here and try to figure out different functions on your own 
(as stated in Rule 3, also figure out how to propogate missing values as stated in Rule 4)'''
a = np.arange(-15, 15).reshape(5, 6) ** 2
print(a)
print('----------Rule1--------- ')
b = np.full(a.shape,3)
print('----------Rule2--------- ')
print('a + b =\n',a+b)
print('a - b =\n',a-b)
print('a * b =\n',a*b)
print('a / b =\n',a/b)



[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]
----------Rule1--------- 
----------Rule2--------- 
a + b =
 [[228 199 172 147 124 103]
 [ 84  67  52  39  28  19]
 [ 12   7   4   3   4   7]
 [ 12  19  28  39  52  67]
 [ 84 103 124 147 172 199]]
a - b =
 [[222 193 166 141 118  97]
 [ 78  61  46  33  22  13]
 [  6   1  -2  -3  -2   1]
 [  6  13  22  33  46  61]
 [ 78  97 118 141 166 193]]
a * b =
 [[675 588 507 432 363 300]
 [243 192 147 108  75  48]
 [ 27  12   3   0   3  12]
 [ 27  48  75 108 147 192]
 [243 300 363 432 507 588]]
a / b =
 [[75.         65.33333333 56.33333333 48.         40.33333333 33.33333333]
 [27.         21.33333333 16.33333333 12.          8.33333333  5.33333333]
 [ 3.          1.33333333  0.33333333  0.          0.33333333  1.33333333]
 [ 3.          5.33333333  8.33333333 12.         16.33333333 21.33333333]
 [27.         33.33333333 40.33333333 48.         56.33333333 65.333

In [150]:
print('----------Rule3--------- ')
sum_a = np.sum(a)
mean_a = np.mean(a)
std_a = np.std(a)

print("\nSum of array a:", sum_a)
print("Mean of array a:", mean_a)
print("Standard deviation of array a:", std_a)

sum_along_columns = np.sum(a, axis=0)  # Sum along the columns
sum_along_rows = np.sum(a, axis=1)     # Sum along the rows

print("\nSum of array a along columns:", sum_along_columns)
print("Sum of array a along rows:", sum_along_rows)

----------Rule3--------- 

Sum of array a: 2255
Mean of array a: 75.16666666666667
Standard deviation of array a: 67.45323482894567

Sum of array a along columns: [405 380 365 360 365 380]
Sum of array a along rows: [955 271  19 199 811]


6.Create the array below with
                  a = np.arange(-15, 15).reshape(5, 6) ** 2
1. The maximum of each row
2. The mean of each column
3. The position of the overall minimum

In [151]:
# code here and display all 3 values appropriately. You MUST NOT choose an array of your own choice.
a = np.arange(-15, 15).reshape(5, 6) ** 2
print(a)
print('Maximum of each row =',a.max(axis=1))
print('Mean of each row =',a.mean(axis=0))
print('The position of the overall minimum =',a.argmin())

[[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]
Maximum of each row = [225  81   9  64 196]
Mean of each row = [81. 76. 73. 72. 73. 76.]
The position of the overall minimum = 15


# Array Broadcasting
NumPy arrays of different dimensionality can be combined in the same expression. Arrays with smaller dimension are broadcasted to match the larger arrays, without copying data.

Broadcasting has two rules.

RULE 1: PREPEND ONES TO SMALLER ARRAY'S SHAPE

RULE 2: DIMENSIONS OF SIZE 1 ARE REPEATED WITHOUT COPYING

In [152]:
#code here # Create 2 arrays A and B with dim (5,4) and (5,) respectively, apply addition and subtraction.

A = np.arange(20).reshape(5, 4)
print("Array A:\n", A)
B = np.arange(5)
print("\nArray B:\n", B)

# It is not possible to perform arithmetic operation on the arrays having different shapes
# we will use broadcasting to apply the operations
# Addition and subtraction
print("\nAddition =\n",A + B[:, np.newaxis])
print("\nSubtraction =\n",A - B[:, np.newaxis])
 

Array A:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Array B:
 [0 1 2 3 4]

Addition =
 [[ 0  1  2  3]
 [ 5  6  7  8]
 [10 11 12 13]
 [15 16 17 18]
 [20 21 22 23]]

Subtraction =
 [[ 0  1  2  3]
 [ 3  4  5  6]
 [ 6  7  8  9]
 [ 9 10 11 12]
 [12 13 14 15]]


1.Use reduce() operation on an array to reduec it into a single meaningful value. You. can also use a specific axis to apply reduce operation.

2.accumulate() creates a new array containing the intermediate results of the reduce operation at each element in a.


In [153]:
# Answer here (use both of these functions on an array of your own choice)

### We will work with the following array:

In [154]:
a = np.arange(25).reshape(5, 5)
a
#moving forward, you must use this array for the operations

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Use slicing only to select 3rd and last row along with 2nd and last columns

In [155]:
# Answer here
a[[2, -1], :][:, [1, -1]]

array([[11, 14],
       [21, 24]])

# Extract the following sub-array: [[2, 3], [12, 13], [22, 23]]

In [156]:
# Answer here
sub_array = a[0:5:2, 2:4]

print("\nExtracted sub-array:\n", sub_array)


Extracted sub-array:
 [[ 2  3]
 [12 13]
 [22 23]]


# Combine fancy/location indexing with slicing to extract the following sub-array: [[6, 8], [16, 18], [21, 23]]

In [157]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [158]:
# Answer here
a[[1, 3, 4], 1:5:2]

array([[ 6,  8],
       [16, 18],
       [21, 23]])

# Change the values 1, 10, 19 and 22 in the array to -2

In [159]:
# Answer
a[0, 1] = -2  # Value 1
a[2, 0] = -2  # Value 10
a[3, 4] = -2  # Value 19
a[4, 2] = -2  # Value 22

# Repeat above using boolean indexing

In [160]:
# Answer here
# Create a boolean mask for the values 1, 10, 19, and 22
mask = (a == 1) | (a == 10) | (a == 19) | (a == 22)
a[mask] = -2
a

array([[ 0, -2,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [-2, 11, 12, 13, 14],
       [15, 16, 17, 18, -2],
       [20, 21, -2, 23, 24]])

# Combine slicing in the column dimension and boolean indexing in row dimension to extract the following sub-array: [[0, 3], [10, 13], [15, 18]]

In [161]:
# Answer here
row_mask = (a[:, 0] == 0) | (a[:, 0] == 10) | (a[:, 0] == 15)
a[row_mask, ::3]

array([[ 0,  3],
       [15, 18]])

# Calculating the sum, min and max of all diagonal values

In [162]:
# Answer here
diagonal_values = np.diagonal(a)
print("\nDiagonal values:", diagonal_values)

# Calculate sum, min, and max of diagonal values
diagonal_sum = np.sum(diagonal_values)
diagonal_min = np.min(diagonal_values)
diagonal_max = np.max(diagonal_values)

print("\nSum of diagonal values:", diagonal_sum)
print("Minimum of diagonal values:", diagonal_min)
print("Maximum of diagonal values:", diagonal_max)


Diagonal values: [ 0  6 12 18 24]

Sum of diagonal values: 60
Minimum of diagonal values: 0
Maximum of diagonal values: 24


# Calculate the sum of differences between the 2nd row and 2nd last column

In [163]:
# Answer here
# Extract the 2nd row (index 1) and the 2nd last column (index -2)
second_row = a[1, :]
second_last_column = a[:, -2]

# Calculate the element-wise differences
differences = second_row - second_last_column

# Calculate the sum of the differences
sum_of_differences = np.sum(differences)

print("\nSecond row:", second_row)
print("Second last column:", second_last_column)
print("Element-wise differences:", differences)
print("Sum of differences:", sum_of_differences)


Second row: [5 6 7 8 9]
Second last column: [ 3  8 13 18 23]
Element-wise differences: [  2  -2  -6 -10 -14]
Sum of differences: -30


# Create a new array that is the sum of even rows and odd rows

In [165]:
# Define the array
a = np.array([[225, 196, 169, 144, 121, 100],
              [ 81,  64,  49,  36,  25,  16],
              [  9,   4,   1,   0,   1,   4],
              [  9,  16,  25,  36,  49,  64],
              [ 81, 100, 121, 144, 169, 196]])

print("Array a:\n", a)

# Extract even-indexed rows (0, 2, 4)
even_rows = a[::2]

# Extract odd-indexed rows (1, 3)
odd_rows = a[1::2]

# Calculate the sum of even rows and odd rows
sum_even_rows = np.sum(even_rows, axis=0)
sum_odd_rows = np.sum(odd_rows, axis=0)

# Combine the sums into a new array
result_array = np.array([sum_even_rows, sum_odd_rows])

print("\nSum of even rows:", sum_even_rows)
print("Sum of odd rows:", sum_odd_rows)
print("Resulting array:\n", result_array)

Array a:
 [[225 196 169 144 121 100]
 [ 81  64  49  36  25  16]
 [  9   4   1   0   1   4]
 [  9  16  25  36  49  64]
 [ 81 100 121 144 169 196]]

Sum of even rows: [315 300 291 288 291 300]
Sum of odd rows: [90 80 74 72 74 80]
Resulting array:
 [[315 300 291 288 291 300]
 [ 90  80  74  72  74  80]]


## You are done. Good job!