In [196]:
#import the required libraries
import numpy as np

# Step 1 : Read the Data!

In [197]:
#give path of the source-file and store that path in a variable named census
census='./data/makeSenseOfCensus.csv'

# Loading the data

You have studied getfromtext in Numpy Classes, now is the time to put it into action :) Below is the half completed code, you have to substitute values for delimiter and skip_header in it for hte data to be properly read into a Data array. The output of the array has been shared with you guys followed by the code block

In [198]:
data = np.genfromtxt(census, delimiter =',' , skip_header =1 )
print("\nData:\n\n ", data)


Data:

  [[39. 13.  4. ...  0. 40.  0.]
 [50. 13.  4. ...  0. 13.  0.]
 [38.  9.  4. ...  0. 40.  0.]
 ...
 [48. 13.  4. ...  0. 58.  1.]
 [40. 10.  4. ...  0. 40.  0.]
 [39. 13.  4. ...  0. 50.  1.]]


# Printing the type of data

In [199]:
#print the type of data
print("\nType of data structure:", type(census))


Type of data structure: <class 'str'>


# Step 2 : Append the Data

A new record [[50,9,4,1,0,0,40,0]] has been given to you. You are supposed to append this new record into the data using np.concatenate()

In [200]:
new_record = [[50,9,4,1,0,0,40,0]]

## Append 'new_record' (given) to 'data' using "np.concatenate()"

In [201]:
new_record = np.array(new_record)
census=np.concatenate((data,new_record),axis=0)

In [202]:
#display after appending the new record at the end of the array.
census

array([[39., 13.,  4., ...,  0., 40.,  0.],
       [50., 13.,  4., ...,  0., 13.,  0.],
       [38.,  9.,  4., ...,  0., 40.,  0.],
       ...,
       [40., 10.,  4., ...,  0., 40.,  0.],
       [39., 13.,  4., ...,  0., 50.,  1.],
       [50.,  9.,  4., ...,  0., 40.,  0.]])

# Step 3 : Check if it's a young country or old country

 Create a new array called 'age' by taking only age column(age is the column with index 0) of 'census' array.

In [203]:
age=census[0:,0]
age

array([39., 50., 38., ..., 40., 39., 50.])

Find the max age and store it in a variable called 'max_age'.



In [204]:
#print the max_age
max_age=np.max(age)
print('The Maximum Age is :',max_age)

The Maximum Age is : 90.0


Find the min age and store it in a variable called 'min_age'.

In [205]:
#print the min_age
min_age=np.min(age)
print('The Minimum Age is :',min_age)

The Minimum Age is : 17.0


Find the mean of the age and store it in a variable called 'age_mean'.

In [206]:
#print the age_mean
age_mean=np.mean(age)
print('The Mean of Age is :',age_mean)

The Mean of Age is : 38.06293706293706


Find the standard deviation of the age and store it in a variable called 'age_std'

In [207]:
#print the age_std
age_std=np.std(age)
print('The Standard Deviation of Age is :',age_std)

The Standard Deviation of Age is : 13.341478176165857


# Step 4: Let's check the country's race distribution to identify the minorities

Create four different arrays by subsetting 'census' array by Race column(Race is the column with index 2) and save them in 'race_0','race_1', 'race_2', 'race_3' and 'race_4' respectively(Meaning: Store the array where 'race'column has value 0 in 'race_0', so on and so forth)

In [208]:
race_0=census[census[0:,2]==0]
race_1=census[census[0:,2]==1]
race_2=census[census[0:,2]==2]
race_3=census[census[0:,2]==3]
race_4=census[census[0:,2]==4]

In [209]:
# Display the results
print("Race 0:\n", race_0)
print("Race 1:\n", race_1)
print("Race 2:\n", race_2)
print("Race 3:\n", race_3)
print("Race 4:\n", race_4)


Race 0:
 [[34.  4.  0.  1.  0.  0. 45.  0.]
 [35. 10.  0.  0.  0.  0. 40.  0.]
 [60.  6.  0.  0.  0.  0. 10.  0.]
 [51.  9.  0.  1.  0.  0. 40.  0.]
 [25. 10.  0.  0.  0.  0. 20.  0.]
 [20.  9.  0.  1.  0.  0. 48.  0.]
 [23. 10.  0.  0.  0.  0. 25.  0.]
 [29.  9.  0.  1.  0.  0. 40.  0.]
 [27. 12.  0.  1.  0.  0. 40.  0.]
 [31. 12.  0.  0.  0.  0. 40.  0.]]
Race 1:
 [[3.000e+01 1.300e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [4.000e+01 1.100e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [5.400e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 6.000e+01
  1.000e+00]
 [3.000e+01 9.000e+00 1.000e+00 0.000e+00 0.000e+00 1.573e+03 3.500e+01
  0.000e+00]
 [4.900e+01 1.000e+01 1.000e+00 1.000e+00 0.000e+00 0.000e+00 4.000e+01
  1.000e+00]
 [3.300e+01 1.300e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [4.400e+01 1.400e+01 1.000e+00 0.000e+00 0.000e+00 0.000e+00 4.000e+01
  0.000e+00]
 [2.800e+01 9.000e+00 1.000e+00 0.00

Store the length of the above created arrays in 'len_0', 'len_1','len_2', 'len_3' and 'len_4' respectively

In [210]:
#len_0
len_0=race_0.shape[0]
print("Length of the race_0 is:", len_0)

Length of the race_0 is: 10


In [211]:
#len_1
len_1=race_1.shape[0]
print("Length of the race_1 is:", len_1)

Length of the race_1 is: 27


In [212]:
#len_2
len_2=race_2.shape[0]
print("Length of the race_2 is:", len_2)

Length of the race_2 is: 110


In [213]:
#len_3
len_3=race_3.shape[0]
print("Length of the race_3 is:", len_3)

Length of the race_3 is: 6


In [214]:
#len_4
len_4=race_4.shape[0]
print("Length of the race_0 is:", len_4)

Length of the race_0 is: 848


Find out which is the race with the minimum no. of citizens

In [215]:
lengths = [len_0, len_1, len_2, len_3, len_4]

# Find the race with the minimum number of citizens
min_length = np.min(lengths)
min_index = np.argmin(lengths)

# Print the race with the minimum number of citizens
print(f"The race with the minimum number of citizens is: race_{min_index} with {min_length} citizens.")


The race with the minimum number of citizens is: race_3 with 6 citizens.


Find out which is the race with the maximum no. of citizens

In [216]:
lengths = [len_0, len_1, len_2, len_3, len_4]
# Find the race with the maximum number of citizens
max_length = np.max(lengths)
max_index = np.argmax(lengths)

# Print the race with the maximum number of citizens
print(f"The race with the minimum number of citizens is: race_{max_index} with {max_length} citizens.")

The race with the minimum number of citizens is: race_4 with 848 citizens.


Store the number associated with the minority race in a variable called 'minority_race'(For eg: if "len(race_5)" is the minimum, store 5 in 'minority_race' because that is the index of the race having the least no. of citizens )

In [217]:
race_lengths=[len_0,len_1,len_2,len_3,len_4]
# Find the index of the race with the minimum number of citizens
minority_race = np.argmin(race_lengths)

# Print the minority race index
print(f"The minority race is: race_{minority_race} with {race_lengths[minority_race]} citizens.")

The minority race is: race_3 with 6 citizens.


# Step 5: As per govt. records citizens above 60 should not work more than 25 hours a week. Let us check if the policy is in place

a.Create a new subset array called 'senior_citizens' by filtering 'census' according to age>60 (age is the column with index 0)

[Row,Columns]  :

In [218]:
#from age column, filter out age data > 60
senior_citizens = census[census[:, 0] > 60]

b.Add all the working hours(working hours is the column with index 6) of 'senior_citizens' and store it in a variable called 'working_hours_sum'

In [219]:
working_hours_sum=senior_citizens[0:,6].sum()
working_hours_sum

1917.0

c.Find the length of 'senior_citizens' and store it in a variable called 'senior_citizens_len'

In [220]:
senior_citizens_len=senior_citizens.shape[0]
senior_citizens_len

61

d. Finally find the average working hours of the senior citizens by dividing 'working_hours_sum' by 'senior_citizens_len' and store it in a variable called 'avg_working hours'.

In [221]:
avg_working_hours=working_hours_sum/senior_citizens_len
avg_working_hours

31.42622950819672

e. Print 'avg_working_hours' and see if the govt. policy is followed.

In [222]:
if avg_working_hours < 25 :
    print('The Goverment Policy is being Followed')
else:
    print('The Goverment Policy is not being Followed')

The Goverment Policy is not being Followed


# Step 6: Let's check that higher educated people have better pay in general.

Create two new subset arrays called 'high' and 'low' by filtering 'census' according to education-num>10 and education-num<=10 (education-num is the column with index 1) respectively.



In [223]:
high=census[census[0:,1]>10]
low=census[census[0:,1]<=10]

Find the mean of income column(income is the column with index 7) of 'high' array and store it in 'avg_pay_high'. Do the same for 'low' array and store it's mean in 'avg_pay_low'.

In [224]:
avg_pay_high = high[:, 7].mean()
print("Average pay for high income group:", avg_pay_high)

Average pay for high income group: 0.42813455657492355


In [225]:
avg_pay_low = low[:, 7].mean()
print("Average pay for low income group:", avg_pay_low)

Average pay for low income group: 0.13649851632047477
